// Curated real wedding photos (public-domain / CC-licensed, sourced from Wikimedia Commons)
// hotlinked as static URLs — no API calls, no rate limits, no auth needed for the demo.

export const CURATED_IMAGES = [
  { title: "Wedding Venue", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Royal_Wedding_Stockholm_2010-Slottsbacken-05_edit.jpg/960px-Royal_Wedding_Stockholm_2010-Slottsbacken-05_edit.jpg" },
  { title: "Wedding Venue", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Christian_wedding_in_Russia.jpg/960px-Christian_wedding_in_Russia.jpg" },
  { title: "Wedding Venue", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Wedding_venue_of_Marizon_northeast_fa%C3%A7ade_on_the_pier_at_902-1_Momochihama-2-ch%C5%8Dme_Sawara-ku_Fukuoka_City_20221130.jpg/960px-Wedding_venue_of_Marizon_northeast_fa%C3%A7ade_on_the_pier_at_902-1_Momochihama-2-ch%C5%8Dme_Sawara-ku_Fukuoka_City_20221130.jpg" },
  { title: "Wedding Venue", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Chateau_de_Tourreau_-_Provence%2C_France_-_Wedding_Photography_01.jpg/960px-Chateau_de_Tourreau_-_Provence%2C_France_-_Wedding_Photography_01.jpg" },
  { title: "Wedding Venue", url: "https://upload.wikimedia.org/wikipedia/commons/7/73/Shiloh_wedding_venue.jpg" },
  { title: "Outdoor Ceremony", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Allan-highlandwedding1780.jpg/960px-Allan-highlandwedding1780.jpg" },
  { title: "Outdoor Ceremony", url: "https://upload.wikimedia.org/wikipedia/commons/6/68/COLLECTIE_TROPENMUSEUM_Bevolking_rond_een_feestmaal_ter_gelegenheid_van_een_huwelijksfeest_te_Tedjakoele_TMnr_60042403.jpg" },
  { title: "Outdoor Ceremony", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/The_Mansion_Outdoor_wedding.jpg/960px-The_Mansion_Outdoor_wedding.jpg" },
  { title: "Outdoor Ceremony", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/StateLibQld_1_189779_Outdoor_wedding_being_performed_under_the_Burke_and_Wills_tree%2C_near_Boulia%2C_Queensland%2C_1920s.jpg/960px-StateLibQld_1_189779_Outdoor_wedding_being_performed_under_the_Burke_and_Wills_tree%2C_near_Boulia%2C_Queensland%2C_1920s.jpg" },
  { title: "Outdoor Ceremony", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Outdoor_Wedding_%288802068101%29.jpg/960px-Outdoor_Wedding_%288802068101%29.jpg" },
  { title: "Outdoor Ceremony", url: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Bear_Creek_Lake_Wedding_2013_%2814193295295%29.jpg" },
  { title: "Reception Decor", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL.jpg/960px-Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL.jpg" },
  { title: "Reception Decor", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54210764627.jpg/960px-Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54210764627.jpg" },
  { title: "Reception Decor", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54211662881.jpg/960px-Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54211662881.jpg" },
  { title: "Reception Decor", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54211893133.jpg/960px-Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54211893133.jpg" },
  { title: "Reception Decor", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54211894028.jpg/960px-Reception_Room%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL_-_54211894028.jpg" },
  { title: "Reception Decor", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Reception_Room_Fireplace%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL.jpg/960px-Reception_Room_Fireplace%2C_Samuel_M._Nickerson_Mansion%2C_Driehaus_Museum%2C_Erie_Street_and_Wabash_Avenue%2C_River_North%2C_Chicago%2C_IL.jpg" },
  { title: "Floral Centerpiece", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Arreglo_floral_-_boda_en_La_Toscana.jpg/960px-Arreglo_floral_-_boda_en_La_Toscana.jpg" },
  { title: "Bridal Bouquet", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Bridal_bouquet_white_pink_rose_stephanotis.jpg/960px-Bridal_bouquet_white_pink_rose_stephanotis.jpg" },
  { title: "Bridal Bouquet", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Hochzeit_-_Brautstraeusse.JPG/960px-Hochzeit_-_Brautstraeusse.JPG" },
  { title: "Bridal Bouquet", url: "https://upload.wikimedia.org/wikipedia/commons/0/06/Wedding_bouquet_white_roses.jpg" },
  { title: "Bridal Bouquet", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Bridal_Bouquet_%281%29_%282213031672%29.jpg/960px-Bridal_Bouquet_%281%29_%282213031672%29.jpg" },
  { title: "Bridal Bouquet", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Bridal_Bouquet_%282%29_%282213030464%29.jpg/960px-Bridal_Bouquet_%282%29_%282213030464%29.jpg" },
  { title: "Wedding Cake", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Wedding_cake_%28undecorated%29.JPG/960px-Wedding_cake_%28undecorated%29.JPG" },
  { title: "Wedding Cake", url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Wedding_Cake_-_With_Roses.jpg" },
  { title: "Wedding Cake", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Wedding_cake_-_Kathmandu%2C_Nepal_on_2018.jpg/960px-Wedding_cake_-_Kathmandu%2C_Nepal_on_2018.jpg" },
  { title: "Wedding Cake", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Wedding_cake_in_arrangements_for_a_modern_wedding_at_Cotonou_town_in_Benin.jpg/960px-Wedding_cake_in_arrangements_for_a_modern_wedding_at_Cotonou_town_in_Benin.jpg" },
  { title: "Reception Lighting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Vietnamese_wedding_reception.jpg/960px-Vietnamese_wedding_reception.jpg" },
  { title: "Reception Lighting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Reception_table_setting.jpg/960px-Reception_table_setting.jpg" },
  { title: "Reception Lighting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Reception_stage_with_Lighting.jpg/960px-Reception_stage_with_Lighting.jpg" },
  { title: "Reception Lighting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Candlelight_Dinner_-_Earth_Hour_-1_%282370211677%29.jpg/960px-Candlelight_Dinner_-_Earth_Hour_-1_%282370211677%29.jpg" },
  { title: "Reception Lighting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Candlelight_Dinner_-_Earth_Hour_-2_%282371047914%29.jpg/960px-Candlelight_Dinner_-_Earth_Hour_-2_%282371047914%29.jpg" },
  { title: "Wedding Dress", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/White-wedding-dress.jpg/960px-White-wedding-dress.jpg" },
  { title: "Wedding Dress", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Bride_getting_dressed.jpg/960px-Bride_getting_dressed.jpg" },
  { title: "Wedding Dress", url: "https://upload.wikimedia.org/wikipedia/commons/9/95/Woman_in_wedding_dress_with_bouquet_of_red_flowers.jpg" },
  { title: "Wedding Dress", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Wedding_Dress_For_Happy_Couple_in_Love.jpg/960px-Wedding_Dress_For_Happy_Couple_in_Love.jpg" },
  { title: "Wedding Dress", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Beautiful_Chinese_Bride_in_White_Wedding_Dress.jpg/960px-Beautiful_Chinese_Bride_in_White_Wedding_Dress.jpg" },
  { title: "Wedding Dress", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Kuwaiti_Wedding_Dress.jpg/960px-Kuwaiti_Wedding_Dress.jpg" },
  { title: "Wedding Rings", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Weddingring.JPG/960px-Weddingring.JPG" },
  { title: "Wedding Rings", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Wedding_rings_and_roses.jpg/960px-Wedding_rings_and_roses.jpg" },
  { title: "Wedding Rings", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Placing_a_wedding_ring.jpg/960px-Placing_a_wedding_ring.jpg" },
  { title: "Wedding Rings", url: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Titanium-Wedding-Band-n11-01.jpg" },
  { title: "Wedding Rings", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Wedding_rings_%28Unsplash%29.jpg/960px-Wedding_rings_%28Unsplash%29.jpg" },
  { title: "Wedding Rings", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Groom_touching_wedding_band_%28Unsplash%29.jpg/960px-Groom_touching_wedding_band_%28Unsplash%29.jpg" },
  { title: "Boho Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/1/12/Bouquet_di_Fiori_Finti.jpg" },
  { title: "Boho Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Boho_flower_crown%2C_ivory_rose_headband%2C_woodland_wedding_head_piece_-_frou_frou2.jpg" },
  { title: "Garden Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Story_Garden_%22Garden_Wedding%22_in_Holon%2C_Israel.JPG/960px-Story_Garden_%22Garden_Wedding%22_in_Holon%2C_Israel.JPG" },
  { title: "Garden Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Wedding_Supper_-_Martin_van_Meytens_-_Google_Cultural_Institute.jpg/960px-Wedding_Supper_-_Martin_van_Meytens_-_Google_Cultural_Institute.jpg" },
  { title: "Garden Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Wedding_photos_-_Chengdu_Botanical_Garden_-_Chengdu%2C_China_-_DSC03567.JPG/960px-Wedding_photos_-_Chengdu_Botanical_Garden_-_Chengdu%2C_China_-_DSC03567.JPG" },
  { title: "Garden Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Wedding_photos_-_Chengdu_Botanical_Garden_-_Chengdu%2C_China_-_DSC03628.JPG/960px-Wedding_photos_-_Chengdu_Botanical_Garden_-_Chengdu%2C_China_-_DSC03628.JPG" },
  { title: "Garden Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Wedding_photos_-_Chengdu_Botanical_Garden_-_Chengdu%2C_China_-_DSC03630.JPG/960px-Wedding_photos_-_Chengdu_Botanical_Garden_-_Chengdu%2C_China_-_DSC03630.JPG" },
  { title: "Garden Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hollis_Garden_wedding_shoot.jpg/960px-Hollis_Garden_wedding_shoot.jpg" },
  { title: "Barn Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Pieter_Brueghel_de_Jonge_-_Bruiloftsmaal_in_de_schuur_%28MSK_Gent%29.jpg/960px-Pieter_Brueghel_de_Jonge_-_Bruiloftsmaal_in_de_schuur_%28MSK_Gent%29.jpg" },
  { title: "Barn Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Detail_of_Pieter_II_Brueghel%27s_The_Peasant_Wedding_in_a_Barn.jpg/960px-Detail_of_Pieter_II_Brueghel%27s_The_Peasant_Wedding_in_a_Barn.jpg" },
  { title: "Barn Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Pieter_Brueghel_de_Jonge_%281564of65-1638%29_Bruiloftsmaal_in_de_schuur_-_MSK_Gent_25-4-2018.JPG/960px-Pieter_Brueghel_de_Jonge_%281564of65-1638%29_Bruiloftsmaal_in_de_schuur_-_MSK_Gent_25-4-2018.JPG" },
  { title: "Barn Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Wiki_Loves_Art_-_Gent_-_Museum_voor_Schone_Kunsten_-_Bruiloftsmaal_in_de_schuur_%28Q21680607%29_%282%29-cropped.jpg/960px-Wiki_Loves_Art_-_Gent_-_Museum_voor_Schone_Kunsten_-_Bruiloftsmaal_in_de_schuur_%28Q21680607%29_%282%29-cropped.jpg" },
  { title: "Barn Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Bruiloftsmaal_in_de_schuur%2C_Pieter_Brueghel_de_Jonge%2C_1616%2C_Koninklijk_Museum_voor_Schone_Kunsten_Gent%2C_S-46.jpg/960px-Bruiloftsmaal_in_de_schuur%2C_Pieter_Brueghel_de_Jonge%2C_1616%2C_Koninklijk_Museum_voor_Schone_Kunsten_Gent%2C_S-46.jpg" },
  { title: "Barn Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/MSK_Gent_30.jpg/960px-MSK_Gent_30.jpg" },
  { title: "Beach Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Wedding_on_the_Beach_Modern_Art_Photograph.jpg/960px-Wedding_on_the_Beach_Modern_Art_Photograph.jpg" },
  { title: "Beach Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/A_wedding_couple_at_Paltaniemi_beach%2C_Kajaani.JPG/960px-A_wedding_couple_at_Paltaniemi_beach%2C_Kajaani.JPG" },
  { title: "Beach Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Wedding_Beach%2C_Makena.jpg/960px-Wedding_Beach%2C_Makena.jpg" },
  { title: "Beach Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Wedding_on_the_beach%2C_Pass-a-Grille_Beach%2C_St._Pete_Beach.jpg/960px-Wedding_on_the_beach%2C_Pass-a-Grille_Beach%2C_St._Pete_Beach.jpg" },
  { title: "Beach Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Beach_Wedding_Party_%28449235931%29.jpg/960px-Beach_Wedding_Party_%28449235931%29.jpg" },
  { title: "Beach Wedding", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Beach_wedding_photograph_of_a_Turkish_couple.jpg/960px-Beach_wedding_photograph_of_a_Turkish_couple.jpg" },
  { title: "Wedding Arch", url: "https://upload.wikimedia.org/wikipedia/commons/2/29/Xcalacoco_Wedding_Arch_-_panoramio.jpg" },
  { title: "Wedding Arch", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/FS_wedding_arch_%2814055030198%29.jpg/960px-FS_wedding_arch_%2814055030198%29.jpg" },
  { title: "Wedding Arch", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/The_wedding_arch_LCCN2016645727.jpg/960px-The_wedding_arch_LCCN2016645727.jpg" },
  { title: "Wedding Arch", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/The_Wedding_Arch_%2814611841596%29.jpg/960px-The_Wedding_Arch_%2814611841596%29.jpg" },
  { title: "Wedding Arch", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Wedding_on_Stone_Arch_Bridge_City_Park_New_Orleans.jpg/960px-Wedding_on_Stone_Arch_Bridge_City_Park_New_Orleans.jpg" },
  { title: "Wedding Arch", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Arch_of_Reno_Wedding_Chapel_-_Reno_-_Sarah_Stierch.jpg/960px-Arch_of_Reno_Wedding_Chapel_-_Reno_-_Sarah_Stierch.jpg" },
  { title: "Table Setting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Table_setting_during_a_German_wedding_party_showing_a_simple_example_of_decorative_napkin_folding_2006.jpg/960px-Table_setting_during_a_German_wedding_party_showing_a_simple_example_of_decorative_napkin_folding_2006.jpg" },
  { title: "Table Setting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Wedding_Banquet_setting.jpeg/960px-Wedding_Banquet_setting.jpeg" },
  { title: "Table Setting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/StateLibQld_1_126067_Wedding_breakfast_table_setting_inside_the_Central_Hotel%2C_Hughenden%2C_1905.jpg/960px-StateLibQld_1_126067_Wedding_breakfast_table_setting_inside_the_Central_Hotel%2C_Hughenden%2C_1905.jpg" },
  { title: "Table Setting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Reception_table_setting.jpg/960px-Reception_table_setting.jpg" },
  { title: "Table Setting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Wedding_table_%28AM_86962-1%29.jpg/960px-Wedding_table_%28AM_86962-1%29.jpg" },
  { title: "Table Setting", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Table_setting_for_the_Redwood-Ottaway_wedding_and_Ottaway_house%2C_1909.jpg/960px-Table_setting_for_the_Redwood-Ottaway_wedding_and_Ottaway_house%2C_1909.jpg" },
  { title: "Invitation Design", url: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wedding-invitation-cards.jpg" },
  { title: "Invitation Design", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Cover_of_a_Chinese_wedding_invitation_card_..JPG/960px-Cover_of_a_Chinese_wedding_invitation_card_..JPG" },
  { title: "Invitation Design", url: "https://upload.wikimedia.org/wikipedia/commons/3/31/Farah_and_Shah_wedding_invitation_letter.jpg" },
  { title: "Invitation Design", url: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Wedding_Invitation_page_2.jpg" },
  { title: "Invitation Design", url: "https://upload.wikimedia.org/wikipedia/commons/1/12/Wedding_Invitation_Pirie_McCausland_June_12_1889_Toronto.jpg" },
  { title: "Invitation Design", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/1980-10-12_Stan_et_Chris_Invite_R.jpg/960px-1980-10-12_Stan_et_Chris_Invite_R.jpg" },
].map((img, i) => ({ id: `wiki_${i}`, thumb: img.url, source: 'Wikimedia Commons', ...img }))

export function curatedFeed(offset, count) {
  return CURATED_IMAGES.slice(offset, offset + count)
}

export const CURATED_TOTAL = CURATED_IMAGES.length
